title: Tatu Arvela
email: contact@tatuarvela.com
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://tatuarvela.com' # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
